### ISSUE TITLE
Swagger Documentation

### ISSUE THREAD

**Issue by Francesca-Carta** [mia-platform/Mia-service-Net-Library#7]

**Comment by fabio-grieco** [comment]
As a library user, I want to access the documentation so I can see the library REST APIs.

**ACCEPTANCE TESTS**
Swagger documentation is generated for the library REST APIs (status routes).

**Comment by fredmaggiowski** [comment]
Status Routes are not related to swagger documentation. As a user I expect to be able to call a standard `/documentations` API that provides the swagger definition of all the REST API defined by the developer.

Status Routes are another thing that's not related to the swagger (they should not appear in it)
