### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Francesca-Carta** [mia-platform/Mia-service-Net-Library#8]

**Comment by fabio-grieco** [comment]
As a developer, I want to be able to log useful information within my microservice.

**ACCEPTANCE TEST**
A logger instance is available inside the controller that handles the routes.

**Comment by fredmaggiowski** [comment]
Logging should be available for each request, must be in json and should follow [Mia-Platform Guidelines](https://docs.mia-platform.eu/development_suite/monitoring-dashboard/dev_ops_guide/log/).

Also for each request two logs must be generated, one for the incoming request and one for the request completed. Check out these projects for some examples on how it has been implemented:

 * [lc39](https://github.com/mia-platform/lc39/blob/master/lib/custom-logger.js#L43)
 * [glogger](https://github.com/mia-platform/glogger/blob/master/logmiddleware.go#L44) (note that this library is still using the old logging format, logged keys must be aligned with the ones in lc39).
