### ISSUE TITLE
Client HTTP instance (get service proxy, get direct service proxies)

### ISSUE THREAD

**Issue by Francesca-Carta** [mia-platform/Mia-service-Net-Library#9]

**Comment by fabio-grieco** [comment]
As a developer I want to get a client instance which allows me to make HTTP calls to other services.

**ACCEPTANCE TESTS**
- The developer can get the client instance through a class, either by specifying the target service name (direct service proxy) or by choosing the Microservice Gateway as target service.
- The client allows the developer to make HTTP calls through methods named like HTTP verbs.
- Client's HTTP requests reach the target service and the response is received and can be handled.

**Comment by fredmaggiowski** [comment]
In regards of the Microservice Gateway name: it will be provided via an environment variable before starting with this I'd design a proper solution for env var definition and access
